import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import patientInsuranceRoutes from './patient-insurance.routes';
import patientMembershipRoutes from './patient-membership.routes';
import permissionRoutes from './permission.routes';
import practiceInfoRoutes from './practice-info.routes';
import patientRoutes from './patient.routes';
import insuranceCompanyRoutes from './insurance-company.routes';
import insurancePlanRoutes from './insurance-plan.routes';
import ocrRoutes from './ocr.routes';
import allergyRoutes from './allergy.routes';
import appointmentRoutes from './appointment.routes';
import providerRoutes from './provider.routes';
import appointmentTypeRoutes from './appointment-type.routes';
import recurringAppointmentRoutes from './recurring-appointment.routes';
import waitlistRoutes from './waitlist.routes';
import roomRoutes from './room.routes';
import languageRoutes from './language.routes';
import noteTemplateRoutes from './note-template.routes';
import clinicalNoteRoutes from './clinical-note.routes';
import vitalSignRoutes from './vital-sign.routes';
import documentRoutes from './document.routes';
import serviceRoutes from './service.routes';
import invoiceRoutes from './invoice.routes';
import paymentRoutes from './payment.routes';
import estimateRoutes from './estimate.routes';
import authorizationRoutes from './authorization.routes';
import claimRoutes from './claim.routes';
import eraRoutes from './era.routes';
import coverageTemplateRoutes from './coverage-template.routes';
import portalRoutes from './portal.routes';
import adjustmentRoutes from './adjustment.routes';
import depositRoutes from './deposit.routes';
import payPlanRoutes from './payplan.routes';
import financeDashboardRoutes from './finance-dashboard.routes';
import clinicalExamRoutes from './clinical-exam.routes';
import treatmentPlanRoutes from './treatment-plan.routes';
import labCaseRoutes from './lab-case.routes';
import progressNoteRoutes from './progress-note.routes';
import rxRoutes from './rx.routes';
import patientReferralRoutes from './patient-referral.routes';
import reportingRoutes from './reporting.routes';
import audienceRoutes from './audience.routes';
import kpiRoutes from './kpi.routes';
import communicationRoutes from './communication.routes';
import clinicalManagementRoutes from './clinical-management.routes';
import feeManagementRoutes from './fee-management.routes';
import adminFinanceRoutes from './admin-finance.routes';
import paymentTerminalRoutes from './payment-terminal.routes';
import membershipPlanRoutes from './membership-plan.routes';
import medicationRoutes from './medication.routes';
import adjunctiveTherapyRoutes from './adjunctive-therapy.routes';
import aiConversationRoutes from './ai-conversation.routes';
import scheduleBlockRoutes from './schedule-block.routes';
import procedureCodeRoutes from './procedure-code.routes';
import patientImageRouter from './patient-image.route';
import productivityRoutes from './productivity.routes';
import shortlistRoutes from './shortlist.routes';
import notificationRoutes from './notification.routes';
import branchRoutes from './branch.routes';
import practiceGroupRoutes from './practice-group.routes';
import coverageGroupRoutes from './coverage-group.routes';
import formTemplateRoutes from './form-template.routes';
import publicBookingRoutes from './public-booking.routes';
import taskRoutes from './task.routes';

const router = Router();
router.use('/coverage-groups', coverageGroupRoutes);



router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/practice-info', practiceInfoRoutes);
router.use('/patients', patientInsuranceRoutes);
router.use('/patients', patientRoutes);
router.use('/patients', patientMembershipRoutes);
router.use('/insurance-companies', insuranceCompanyRoutes);
router.use('/insurance-plans', insurancePlanRoutes);
router.use('/coverage-templates', coverageTemplateRoutes);
router.use('/ocr', ocrRoutes);
router.use('/allergies', allergyRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/procedure-codes', procedureCodeRoutes);
router.use('/providers', providerRoutes);
router.use('/appointment-types', appointmentTypeRoutes);
router.use('/recurring-appointments', recurringAppointmentRoutes);
router.use('/waitlist', waitlistRoutes);
router.use('/rooms', roomRoutes);
router.use('/languages', languageRoutes);
router.use('/note-templates', noteTemplateRoutes);
router.use('/clinical-notes', clinicalNoteRoutes);
router.use('/vital-signs', vitalSignRoutes);
router.use('/documents', documentRoutes);
router.use('/services', serviceRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/estimates', estimateRoutes);
router.use('/authorizations', authorizationRoutes);
router.use('/claims', claimRoutes);
router.use('/era', eraRoutes);
router.use('/portal', portalRoutes);
router.use('/adjustments', adjustmentRoutes);
router.use('/deposits', depositRoutes);
router.use('/payment-plans', payPlanRoutes);
router.use('/finance-dashboard', financeDashboardRoutes);
router.use('/clinical-exams', clinicalExamRoutes);
router.use('/treatment-plans', treatmentPlanRoutes);
router.use('/lab-cases', labCaseRoutes);
router.use('/progress-notes', progressNoteRoutes);
router.use('/rx', rxRoutes);
router.use('/patient-referrals', patientReferralRoutes);
router.use('/reports', reportingRoutes);
router.use('/audiences', audienceRoutes);
router.use('/kpis', kpiRoutes);
router.use('/communication', communicationRoutes);
router.use('/clinical-management', clinicalManagementRoutes);
router.use('/fee-management', feeManagementRoutes);
router.use('/admin-finance', adminFinanceRoutes);
router.use('/payment-terminals', paymentTerminalRoutes);
router.use('/membership-plans', membershipPlanRoutes);
router.use('/medications', medicationRoutes);
router.use('/patients', adjunctiveTherapyRoutes);
router.use('/ai-conversation', aiConversationRoutes);
router.use('/schedule-blocks', scheduleBlockRoutes);
router.use('/patients/:patientId/images', patientImageRouter);
router.use('/productivity', productivityRoutes);
router.use('/shortlist', shortlistRoutes);
router.use('/notifications', notificationRoutes);
router.use('/branches', branchRoutes);
router.use('/practice-groups', practiceGroupRoutes);
router.use('/form-templates', formTemplateRoutes);
router.use('/public/booking', publicBookingRoutes);
router.use('/tasks', taskRoutes);

export default router;
