import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import practiceInfoRoutes from './practice-info.routes';
import patientRoutes from './patient.routes';
import insuranceCompanyRoutes from './insurance-company.routes';
import ocrRoutes from './ocr.routes';
import allergyRoutes from './allergy.routes';
import appointmentRoutes from './appointment.routes';
import providerRoutes from './provider.routes';
import appointmentTypeRoutes from './appointment-type.routes';
import recurringAppointmentRoutes from './recurring-appointment.routes';
import waitlistRoutes from './waitlist.routes';
import roomRoutes from './room.routes';
import languageRoutes from './language.routes';
import noteTemplateRoutes from './note-template.routes';
import clinicalNoteRoutes from './clinical-note.routes';
import vitalSignRoutes from './vital-sign.routes';
import documentRoutes from './document.routes';
import serviceRoutes from './service.routes';
import invoiceRoutes from './invoice.routes';
import paymentRoutes from './payment.routes';
import estimateRoutes from './estimate.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/practice-info', practiceInfoRoutes);
router.use('/patients', patientRoutes);
router.use('/insurance-companies', insuranceCompanyRoutes);
router.use('/ocr', ocrRoutes);
router.use('/allergies', allergyRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/providers', providerRoutes);
router.use('/appointment-types', appointmentTypeRoutes);
router.use('/recurring-appointments', recurringAppointmentRoutes);
router.use('/waitlist', waitlistRoutes);
router.use('/rooms', roomRoutes);
router.use('/languages', languageRoutes);
router.use('/note-templates', noteTemplateRoutes);
router.use('/clinical-notes', clinicalNoteRoutes);
router.use('/vital-signs', vitalSignRoutes);
router.use('/documents', documentRoutes);
router.use('/services', serviceRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/estimates', estimateRoutes);

export default router;
