/**
 * Default structure for a new patient's medical history form.
 * Used as the base when no saved history exists yet.
 */
export const DEFAULT_MEDICAL_HISTORY = {
  generalInfo: {
    healthEstimate: '',
    physicianName: '',
    physicianSpecialty: '',
    lastExamDate: null,
    purpose: '',
    weight: '',
    weightUnit: 'LBS',
    height: '',
    heightUnit: 'FT/IN',
  },
  premed: {
    requiresPremed: false,
  },
  risk: {
    asaClass: 'ASA 1',
    level: 'low',
  },
  review: {
    reviewedWithPatient: false,
    reviewedAt: null,
    signatureUrl: null,
  },
  sections: [
    {
      id: 'hospitalization',
      number: 1,
      group: 'medical',
      question: 'Hospitalization for illness or injury',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'allergic-reaction',
      number: 2,
      group: 'medical',
      question: 'An allergic or bad reaction to any of the following (Options: Aspirin, Ibuprofen, Acetaminophen, Codeine, Penicillin, Erythromycin, Tetracycline, Sulfa, Local anesthetic, Fluoride, Chlorhexidine, Latex, Nickel, Gold, Silver, Titanium, Nuts, Fruit, Milk, Red dye, Other)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'heart-problems',
      number: 3,
      group: 'medical',
      question: 'Heart problems, or cardiac stent within the last six months (Options: Within the last 6 months, Over 6 months with no symptoms, Over 6 months with symptoms (angina, shortness of breath))',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'infective-endocarditis',
      number: 4,
      group: 'medical',
      question: 'History of infective endocarditis',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'artificial-heart-valve',
      number: 5,
      group: 'medical',
      question: 'Artificial heart valve (Options: Repaired heart defect (PFO))',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'pacemaker',
      number: 6,
      group: 'medical',
      question: 'Pacemaker (Options: Implantable defibrillator, Organ transplant)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'orthopedic-implant',
      number: 7,
      group: 'medical',
      question: 'Orthopedic or soft tissue implant (e.g., joint replacement)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'heart-murmur',
      number: 8,
      group: 'medical',
      question: 'Heart murmur (Options: Rheumatic fever, Scarlet fever)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'blood-pressure',
      number: 9,
      group: 'medical',
      question: 'High or low blood pressure',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'strokes',
      number: 10,
      group: 'medical',
      question: 'Strokes (Options: Within the last 6 months)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'blood-thinners',
      number: 11,
      group: 'medical',
      question: 'Taking blood thinners',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'anemia',
      number: 11,
      group: 'medical',
      question: 'Anemia (Options: Other blood disorder)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'prolonged-bleeding',
      number: 12,
      group: 'medical',
      question: 'Prolonged bleeding due to a slight cut (INR > 3.5) (Options: Past condition, Ongoing condition)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'pneumonia',
      number: 13,
      group: 'medical',
      question: 'Pneumonia (Options: Emphysema, Shortness of breath while sitting without activity, Sarcoidosis)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'chronic-ear-infections',
      number: 14,
      group: 'medical',
      question: 'Chronic ear infections (Options: Tuberculosis, Measles, Chicken pox)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'asthma',
      number: 15,
      group: 'medical',
      question: 'Asthma and other breathing problems (Options: Asthma with occasional use of oral inhaler, Asthma with frequent attacks, Nasal breathing, Stuffy nose, Sinus congestion)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'sleep-problems',
      number: 16,
      group: 'medical',
      question: 'Sleep problems (Options: Sleep apnea, Snoring, Insomnia, Restless sleep, Bedwetting)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'kidney-disease',
      number: 17,
      group: 'medical',
      question: 'Kidney disease (Options: Kidney stone)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'liver-disease',
      number: 18,
      group: 'medical',
      question: 'Liver disease (Options: Jaundice)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'vertigo',
      number: 19,
      group: 'medical',
      question: 'Vertigo (e.g. "the room is spinning")',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'thyroid',
      number: 20,
      group: 'medical',
      question: 'Thyroid (Options: Parathyroid disease, Calcium deficiency)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'hormone-deficiency',
      number: 21,
      group: 'medical',
      question: 'Hormone deficiency or imbalance (e.g. poly cystic ovarian syndrome)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'high-cholesterol',
      number: 22,
      group: 'medical',
      question: 'High cholesterol (Options: Taking statin drugs)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'diabetes',
      number: 23,
      group: 'medical',
      question: 'Diabetes (Options: Type I, Type II, HbA1c / Average blood sugar, Less than 7% / less than 140 mg/dL ~ 7.8 mmol/L, 7-9% / between 140 to 200 mg/dL ~ 7.8 to 11.1 mmol/L, More than 9% / more than 220 mg/dL ~ 12.2 mmol/L)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'stomach-ulcer',
      number: 24,
      group: 'medical',
      question: 'Stomach ulcer (Options: Duodenal ulcer)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'digestive-disorders',
      number: 25,
      group: 'medical',
      question: 'Digestive or eating disorders (Options: Celiac disease, Gastric reflux, Bulimia, Anorexia, Irritable bowel syndrome, Inflammatory bowel disease, Crohn\'s, Other digestive disorders)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'osteoporosis',
      number: 26,
      group: 'medical',
      question: 'Osteoporosis (Options: Osteopenia (i.e. taking bisphosphonates), Ever taken anti-resorptive medications)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'arthritis',
      number: 27,
      group: 'medical',
      question: 'Arthritis (Options: Gout)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'autoimmune-disease',
      number: 28,
      group: 'medical',
      question: 'Autoimmune disease: (Options: Rheumatoid arthritis, Lupus, Scleroderma, Other)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'glaucoma',
      number: 29,
      group: 'medical',
      question: 'Glaucoma',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'contact-lenses',
      number: 30,
      group: 'medical',
      question: 'Contact lenses',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'head-injuries',
      number: 31,
      group: 'medical',
      question: 'Head injuries (Options: Neck injuries)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'epilepsy',
      number: 32,
      group: 'medical',
      question: 'Epilepsy, convulsions (seizures) (Options: Controlled, Frequent)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'neurologic-disorders',
      number: 33,
      group: 'medical',
      question: 'Neurologic disorders: (Options: Alzheimer\'s disease, Dementia, Prion disease)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'viral-infections',
      number: 34,
      group: 'medical',
      question: 'Viral infections (Options: Cold sore, Bacterial infections, Lyme disease)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'lumps-in-mouth',
      number: 35,
      group: 'medical',
      question: 'Lumps in the mouth (Options: Swelling in the mouth)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'hives',
      number: 36,
      group: 'medical',
      question: 'Hives (Options: Skin rash, Hay fever, Other skin disease)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'sti',
      number: 37,
      group: 'medical',
      question: 'STI (Options: STD, HPV)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'hepatitis',
      number: 38,
      group: 'medical',
      question: 'Hepatitis: (Options: Type A, Type B, Type C)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'hiv',
      number: 39,
      group: 'medical',
      question: 'HIV (Options: AIDS)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'tumor',
      number: 40,
      group: 'medical',
      question: 'Tumor (Options: Abnormal growth)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'radiation-therapy',
      number: 41,
      group: 'medical',
      question: 'Radiation therapy',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'chemotherapy',
      number: 42,
      group: 'medical',
      question: 'Chemotherapy (Options: Immunosuppressive medication)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'stress-management',
      number: 43,
      group: 'medical',
      question: 'Difficulties with stress management',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'psychiatric-treatment',
      number: 44,
      group: 'medical',
      question: 'Psychiatric treatment (Options: Antidepressant medication, Mood stabilizing medications)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'concentration-problems',
      number: 45,
      group: 'medical',
      question: 'Concentration problems (Options: ADD/ADHD diagnosis)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'alcohol-consumption',
      number: 46,
      group: 'medical',
      question: 'Occasional alcohol consumption (1 to 4 drinks per week) (Options: Daily alcohol consumption, Recreational drug use)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'other-illness',
      number: 47,
      group: 'medical',
      question: 'Presently being treated for any other illness',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'recent-health-change',
      number: 48,
      group: 'medical',
      question: 'Aware of a change in your health in the last 24 hours (i.e. fever, chills, new cough, or diarrhea)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'weight-management-medication',
      number: 49,
      group: 'medical',
      question: 'Taking medication for weight management',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'supplements-options',
      number: 50,
      group: 'medical',
      question: 'Taking any of the following (Options: Supplements, Probiotics, Vitamins)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'exhausted',
      number: 51,
      group: 'medical',
      question: 'Often exhausted or fatigued',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'headaches',
      number: 52,
      group: 'medical',
      question: 'Experiencing frequent headaches (Options: Experiencing chronic pain)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'smoker',
      number: 53,
      group: 'medical',
      question: 'A smoker (Options: Used to smoke, A smokeless tobacco user, Vaping, An e-cigarette user, A cannabis user)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'sensitive-person',
      number: 54,
      group: 'medical',
      question: 'Considered a touchy / sensitive person',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'unhappy',
      number: 55,
      group: 'medical',
      question: 'Often unhappy (Options: Depressed)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'birth-control',
      number: 56,
      group: 'medical',
      question: 'FEMALE - taking birth control pills',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'pregnant-breastfeeding',
      number: 57,
      group: 'medical',
      question: 'Currently pregnant or breastfeeding (Options: 1st Trimester, 2nd Trimester, 3rd Trimester)',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'prostate-disorder',
      number: 58,
      group: 'medical',
      question: 'Diagnosed with a prostate disorder',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'genital-urinary-disorders',
      number: 59,
      group: 'medical',
      question: 'Other genital and urinary system disorders',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
    {
      id: 'other-surgeries',
      number: 60,
      group: 'medical',
      question: 'Other surgeries',
      answer: 'no',
      comment: '',
      doctorNote: '',
      additionalInfo: '',
    },
  ],
  medications: [],
  supplements: [],
};

/**
 * Default structure for a new patient's dental history form.
 * Used as the base when no saved history exists yet.
 */
export const DEFAULT_DENTAL_HISTORY = {
  sectionSummaries: {
    personalHistory: { risk: '', additionalInfo: '' },
    gumAndBone: { risk: '', additionalInfo: '' },
    toothStructure: { risk: '', additionalInfo: '' },
    biteAndJawJoint: { risk: '', additionalInfo: '' },
    smileCharacteristics: { risk: '', additionalInfo: '' },
  },
  generalInfo: {
    mouthCondition: '',
    previousDentist: '',
    recentExamDate: null,
    recentTreatmentDate: null,
    immediateConcern: '',
    patientSince: '',
    recentXrayDate: null,
    dentistVisitFrequency: '6mo',
  },
  personalHistory: [
    {
      id: 'fearful-treatment',
      number: 1,
      question: 'Are you fearful of dental treatment?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'unfavorable-experience',
      number: 2,
      question: 'Have you had an unfavorable dental experience?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'treatment-complications',
      number: 3,
      question: 'Have you ever had complications from past dental treatment?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'trouble-getting-numb',
      number: 4,
      question: 'Have you ever had trouble getting numb or had any reactions to local anesthetic?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'orthodontic-treatment',
      number: 5,
      question: 'Did you ever have braces, orthodontic treatment or had your bite adjusted, and at what age? (Options: Before 16 years old, After 16 years old, Both)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'missing-teeth-trauma',
      number: 6,
      question: 'Have you had any teeth removed, missing teeth that never developed, or lost teeth due to injury or facial trauma? (Options: Gum disease, Teeth that never developed, Wisdom teeth, Crowding, Caries, Infection, Fracture, Traumatic injuries)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
  ],
  gumAndBone: [
    {
      id: 'bleeding-gums',
      number: 7,
      question: 'Do your gums bleed sometimes or are they ever uncomfortable when brushing or flossing? (Options: Bleeding gums, Painful gums)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'gum-bone-loss',
      number: 8,
      question: 'Have you ever had or been told you have gum loss, gum disease, or bone loss between your teeth? (Options: I have been treated for it, I have not been treated for it)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'unpleasant-taste',
      number: 9,
      question: 'Have you ever noticed an unpleasant taste, odor in your mouth, or swollen and puffy gums?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'family-history-perio',
      number: 10,
      question: 'Is there anyone with a history of periodontal disease in your family?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'gum-recession',
      number: 11,
      question: 'Have you ever experienced gum recession, or can you see more of the roots of your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'loose-teeth',
      number: 12,
      question: 'Have you ever had any teeth become loose on their own (without an injury), or feel them move when chewing?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'burning-sensation',
      number: 13,
      question: 'Have you experienced a burning, painful sensation, or metallic taste in your mouth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
  ],
  toothStructure: [
    {
      id: 'cavities-past-3-years',
      number: 14,
      question: 'Have you had any cavities within the past 3 years?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'saliva-amount',
      number: 15,
      question: 'Does the amount of saliva in your mouth seem too little, not enough, or do you have difficulty swallowing or chewing any food?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'holes-in-teeth',
      number: 16,
      question: 'Do you feel or notice any holes (i.e., pitting, craters) on the biting surface of your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'sensitive-teeth',
      number: 17,
      question: 'Are any teeth sensitive to hot, cold, biting, sweets, or do you avoid brushing any part of your mouth? (Options: Hot, Cold, Biting, Sweet)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'grooves-on-teeth',
      number: 18,
      question: 'Do you have grooves or notches on your teeth near the gum line?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'broken-teeth',
      number: 19,
      question: 'Have you ever broken teeth, chipped teeth, or had a toothache or cracked filling? (Options: Broken teeth, Chipped teeth, Toothache, Cracked filling, Craze lines, Fractured tooth)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'food-caught',
      number: 20,
      question: 'Do you frequently get food caught between any teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'fillings-crowns',
      number: 37,
      question: 'Do you have... (Options: Amalgam fillings, Composite fillings, Gold fillings, Crown, ---, 1 to 4 teeth, 5 to 8 teeth, 9 or more teeth)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
  ],
  biteAndJawJoint: [
    {
      id: 'jaw-joint-pain',
      number: 21,
      question: 'Does your jaw joint ever have pain, sounds (clicking, crackling, or popping), or experience limited opening or locking? (Options: Pain, Sounds, Limited opening, Locking, Popping)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'lower-jaw-backward',
      number: 22,
      question: 'When you bite all of your back teeth together, does it feel like your lower jaw has to move backward, or is being pushed back by your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'facial-muscle-pain',
      number: 23,
      question: 'Do you ever have pain in your facial muscles, or have difficulty chewing gum, raw carrots, nuts, bagels, or other hard, dry foods? (Options: Bagel, Raw carrots, Gum, Nuts, Other)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'teeth-changed',
      number: 24,
      question: 'In the past 5 years, have your teeth changed (become shorter, thinner, or worn) or has your bite changed? (Options: Shorter, Thinner, Worn, 1 to 2 teeth, 3 to 6 teeth, 7 or more teeth)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'crooked-teeth',
      number: 25,
      question: 'Are your teeth becoming more crooked, crowded, or overlapped?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'looser-spaces',
      number: 26,
      question: 'Are any of your teeth becoming looser or are spaces forming between your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'more-than-one-bite',
      number: 27,
      question: 'Do you have more than one bite, or need to squeeze, tap your teeth together, or shift your jaw to make your teeth fit together better?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'tongue-between-teeth',
      number: 28,
      question: 'Do you usually place your tongue between your teeth, use it to push against them, or bite your cheeks or lips?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'oral-habits',
      number: 29,
      question: 'Do you chew ice, bite your nails, use your teeth to hold objects, or have any other oral habits?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'clench-grind',
      number: 30,
      question: 'Do you clench or grind your teeth together in the daytime/nighttime or ever make them sore?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'sleep-problems',
      number: 31,
      question: 'Do you have any problems with sleep (i.e., restlessness or teeth grinding), wake up with a headache or an awareness of your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'bite-appliance',
      number: 32,
      question: 'Have you ever used a bite appliance, Botox, or any medication for clenching, teeth grinding, or jaw discomfort?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
  ],
  smileCharacteristics: [
    {
      id: 'appearance-change',
      number: 33,
      question: 'Is there anything about the appearance of your mouth (smile, lips, teeth, gums) that you would like to change (color, spaces, size, shape, display)? (Options: Too white, Not white enough, Uneven color, Shape, Size, Spacing)',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'bleached-teeth',
      number: 34,
      question: 'Have you ever bleached (whitened) your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'uncomfortable-appearance',
      number: 35,
      question: 'Have you felt uncomfortable or self-conscious about the appearance of your teeth?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
    {
      id: 'disappointed-dental-work',
      number: 36,
      question: 'Have you been disappointed with the appearance of previous dental work?',
      answer: 'No',
      scale: '',
      note: '',
      additionalInfo: '',
      comment: '',
    },
  ],
  review: {
    reviewedWithPatient: false,
    reviewedAt: null,
    signatureDataUrl: null,
  },
};
