import { patientService } from '../services/patient.service';
import { prisma } from '../config/db';

// 25 mock US patients with complete data
const patients = [
  {
    firstName: 'James',
    lastName: 'Harrison',
    middleName: 'Robert',
    preferredName: 'Jim',
    title: 'Mr.',
    dateOfBirth: new Date('1978-04-12'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '901-45-6781',
    phonePrimary: '12145559101',
    phoneSecondary: '12145559102',
    email: 'james.harrison@example.com',
    address: { line1: '142 Maple Street', line2: 'Apt 3B', city: 'Dallas', state: 'TX', postalCode: '75201' },
    emergencyContact: { name: 'Linda Harrison', relationship: 'Spouse', phone: '12145559103' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Software Engineer',
    employer: 'TechCorp Inc.',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '500 Commerce St', city: 'Dallas', state: 'TX', postalCode: '75202' },
    referralSource: 'Google Search',
    notes: 'Patient prefers morning appointments.',
  },
  {
    firstName: 'Maria',
    lastName: 'Gonzalez',
    middleName: 'Elena',
    preferredName: 'Mari',
    title: 'Ms.',
    dateOfBirth: new Date('1990-07-23'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '902-61-4823',
    phonePrimary: '13055559201',
    phoneSecondary: '13055559202',
    email: 'maria.gonzalez@example.com',
    address: { line1: '879 Coral Way', line2: 'Suite 100', city: 'Miami', state: 'FL', postalCode: '33145' },
    emergencyContact: { name: 'Carlos Gonzalez', relationship: 'Brother', phone: '13055559203' },
    preferredLanguage: 'es' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Registered Nurse',
    employer: 'Miami General Hospital',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '1611 NW 12th Ave', city: 'Miami', state: 'FL', postalCode: '33136' },
    referralSource: 'Physician Referral',
    notes: 'Spanish preferred for all written communications.',
  },
  {
    firstName: 'David',
    lastName: 'Kim',
    middleName: 'Sung',
    dateOfBirth: new Date('1985-11-08'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '903-77-5514',
    phonePrimary: '12125559301',
    email: 'david.kim@example.com',
    address: { line1: '215 E 68th Street', city: 'New York', state: 'NY', postalCode: '10065' },
    emergencyContact: { name: 'Susan Kim', relationship: 'Mother', phone: '12125559302' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'sms' as const,
    portalAccessEnabled: false,
    maritalStatus: 'single',
    occupation: 'Financial Analyst',
    employer: 'Goldman Partners LLC',
    patientProfileType: 'adult' as const,
    referralSource: 'Friend Referral',
  },
  {
    firstName: 'Patricia',
    lastName: 'Williams',
    middleName: 'Anne',
    preferredName: 'Pat',
    title: 'Mrs.',
    dateOfBirth: new Date('1962-02-14'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '904-32-8876',
    phonePrimary: '13125559401',
    phoneSecondary: '13125559402',
    email: 'patricia.williams@example.com',
    address: { line1: '3427 N Clark Street', city: 'Chicago', state: 'IL', postalCode: '60657' },
    emergencyContact: { name: 'Robert Williams', relationship: 'Spouse', phone: '13125559403' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'portal' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Teacher',
    employer: 'Chicago Public Schools',
    patientProfileType: 'adult' as const,
    referralSource: 'Insurance Directory',
    notes: 'Has latex allergy on file.',
  },
  {
    firstName: 'Michael',
    lastName: 'Thompson',
    dateOfBirth: new Date('1995-09-30'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '905-88-2341',
    phonePrimary: '16025559501',
    email: 'michael.thompson@example.com',
    address: { line1: '4820 E Indian School Rd', city: 'Phoenix', state: 'AZ', postalCode: '85018' },
    emergencyContact: { name: 'Karen Thompson', relationship: 'Mother', phone: '16025559502' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Graduate Student',
    employer: 'Arizona State University',
    patientProfileType: 'adult' as const,
    referralSource: 'Online Search',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Martinez',
    middleName: 'Rose',
    title: 'Ms.',
    dateOfBirth: new Date('1988-05-17'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '906-14-7723',
    phonePrimary: '14045559601',
    phoneSecondary: '14045559602',
    email: 'jennifer.martinez@example.com',
    address: { line1: '756 Peachtree St NE', line2: 'Apt 12', city: 'Atlanta', state: 'GA', postalCode: '30308' },
    emergencyContact: { name: 'Luis Martinez', relationship: 'Father', phone: '14045559603' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'divorced',
    occupation: 'Marketing Manager',
    employer: 'Delta Creative Agency',
    patientProfileType: 'adult' as const,
    referralSource: 'Yelp Review',
  },
  {
    firstName: 'Robert',
    lastName: 'Johnson',
    middleName: 'Lee',
    title: 'Mr.',
    dateOfBirth: new Date('1955-12-03'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '907-56-3398',
    phonePrimary: '12675559701',
    phoneSecondary: '12675559702',
    email: 'robert.johnson@example.com',
    address: { line1: '1820 Fifth Ave N', city: 'Birmingham', state: 'AL', postalCode: '35203' },
    emergencyContact: { name: 'Betty Johnson', relationship: 'Spouse', phone: '12675559703' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'married',
    occupation: 'Retired',
    patientProfileType: 'adult' as const,
    referralSource: 'Family Referral',
    notes: 'Diabetic patient - monitor blood glucose levels.',
  },
  {
    firstName: 'Ashley',
    lastName: 'Brown',
    dateOfBirth: new Date('2001-03-25'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '908-23-6614',
    phonePrimary: '12065559801',
    email: 'ashley.brown@example.com',
    address: { line1: '4321 Aurora Ave N', city: 'Seattle', state: 'WA', postalCode: '98103' },
    emergencyContact: { name: 'Diane Brown', relationship: 'Mother', phone: '12065559802' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'sms' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Barista',
    employer: 'Starbucks',
    patientProfileType: 'adult' as const,
    referralSource: 'Social Media',
  },
  {
    firstName: 'Christopher',
    lastName: 'Davis',
    middleName: 'Alan',
    title: 'Mr.',
    dateOfBirth: new Date('1972-08-19'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '909-67-1145',
    phonePrimary: '17135559901',
    phoneSecondary: '17135559902',
    email: 'christopher.davis@example.com',
    address: { line1: '6201 Richmond Ave', line2: 'Unit 210', city: 'Houston', state: 'TX', postalCode: '77057' },
    emergencyContact: { name: 'Megan Davis', relationship: 'Spouse', phone: '17135559903' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Petroleum Engineer',
    employer: 'Shell Oil Company',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '150 N Dairy Ashford Rd', city: 'Houston', state: 'TX', postalCode: '77079' },
    referralSource: 'Company Benefit Plan',
  },
  {
    firstName: 'Amanda',
    lastName: 'Wilson',
    middleName: 'Grace',
    preferredName: 'Mandy',
    title: 'Ms.',
    dateOfBirth: new Date('1983-06-27'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '911-34-7782',
    phonePrimary: '16175551001',
    email: 'amanda.wilson@example.com',
    address: { line1: '29 Commonwealth Ave', city: 'Boston', state: 'MA', postalCode: '02116' },
    emergencyContact: { name: 'Thomas Wilson', relationship: 'Father', phone: '16175551002' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'portal' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Attorney',
    employer: 'Sullivan & Cromwell LLP',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '125 Broad St', city: 'Boston', state: 'MA', postalCode: '02110' },
    referralSource: 'Colleague Referral',
  },
  {
    firstName: 'Matthew',
    lastName: 'Anderson',
    middleName: 'Paul',
    dateOfBirth: new Date('1968-10-05'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '912-78-5523',
    phonePrimary: '16155551101',
    phoneSecondary: '16155551102',
    email: 'matthew.anderson@example.com',
    address: { line1: '812 Woodward Ave', city: 'Detroit', state: 'MI', postalCode: '48226' },
    emergencyContact: { name: 'Nancy Anderson', relationship: 'Spouse', phone: '16155551103' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'married',
    occupation: 'Automotive Technician',
    employer: 'Ford Motor Company',
    patientProfileType: 'adult' as const,
    referralSource: 'Union Health Plan',
  },
  {
    firstName: 'Sophia',
    lastName: 'Taylor',
    dateOfBirth: new Date('1997-01-14'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '913-21-8864',
    phonePrimary: '19195551201',
    email: 'sophia.taylor@example.com',
    address: { line1: '318 W Morgan St', city: 'Raleigh', state: 'NC', postalCode: '27601' },
    emergencyContact: { name: 'Carol Taylor', relationship: 'Mother', phone: '19195551202' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'UX Designer',
    employer: 'Red Hat Inc.',
    patientProfileType: 'adult' as const,
    referralSource: 'Online Search',
  },
  {
    firstName: 'Daniel',
    lastName: 'Jackson',
    middleName: 'Wayne',
    title: 'Mr.',
    dateOfBirth: new Date('1975-09-11'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '914-53-2297',
    phonePrimary: '16155551301',
    phoneSecondary: '16155551302',
    email: 'daniel.jackson@example.com',
    address: { line1: '1540 Main St', line2: 'Floor 3', city: 'Columbus', state: 'OH', postalCode: '43215' },
    emergencyContact: { name: 'Cheryl Jackson', relationship: 'Spouse', phone: '16155551303' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'sms' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Construction Manager',
    employer: 'Turner Construction',
    patientProfileType: 'adult' as const,
    referralSource: 'Insurance Directory',
  },
  {
    firstName: 'Emily',
    lastName: 'White',
    middleName: 'Claire',
    preferredName: 'Em',
    title: 'Ms.',
    dateOfBirth: new Date('1993-04-02'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '915-86-4431',
    phonePrimary: '14435551401',
    email: 'emily.white@example.com',
    address: { line1: '901 Light St', city: 'Baltimore', state: 'MD', postalCode: '21230' },
    emergencyContact: { name: 'George White', relationship: 'Father', phone: '14435551402' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Pharmacist',
    employer: 'CVS Health',
    patientProfileType: 'adult' as const,
    referralSource: 'Colleague Referral',
  },
  {
    firstName: 'Joshua',
    lastName: 'Harris',
    dateOfBirth: new Date('1980-07-07'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '916-42-9953',
    phonePrimary: '16155551501',
    phoneSecondary: '16155551502',
    email: 'joshua.harris@example.com',
    address: { line1: '333 W Vine St', city: 'Lexington', state: 'KY', postalCode: '40507' },
    emergencyContact: { name: 'Teresa Harris', relationship: 'Spouse', phone: '16155551503' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'married',
    occupation: 'Veterinarian',
    employer: 'Bluegrass Animal Clinic',
    patientProfileType: 'adult' as const,
    referralSource: 'Friend Referral',
  },
  {
    firstName: 'Olivia',
    lastName: 'Martin',
    middleName: 'Jean',
    title: 'Ms.',
    dateOfBirth: new Date('1999-11-29'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '917-19-3376',
    phonePrimary: '16155551601',
    email: 'olivia.martin@example.com',
    address: { line1: '222 S 4th St', city: 'Louisville', state: 'KY', postalCode: '40202' },
    emergencyContact: { name: 'Frank Martin', relationship: 'Father', phone: '16155551602' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'sms' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Dental Hygienist',
    employer: 'SmileCare Dental',
    patientProfileType: 'adult' as const,
    referralSource: 'Social Media',
  },
  {
    firstName: 'Andrew',
    lastName: 'Garcia',
    middleName: 'Carlos',
    title: 'Mr.',
    dateOfBirth: new Date('1965-03-18'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '918-65-7718',
    phonePrimary: '15055551701',
    phoneSecondary: '15055551702',
    email: 'andrew.garcia@example.com',
    address: { line1: '408 Old Santa Fe Trail', city: 'Santa Fe', state: 'NM', postalCode: '87501' },
    emergencyContact: { name: 'Rosa Garcia', relationship: 'Spouse', phone: '15055551703' },
    preferredLanguage: 'es' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'married',
    occupation: 'Architect',
    employer: 'Garcia & Associates Design',
    patientProfileType: 'adult' as const,
    referralSource: 'Physician Referral',
    notes: 'Hypertension - on lisinopril 10mg daily.',
  },
  {
    firstName: 'Samantha',
    lastName: 'Lee',
    middleName: 'Joy',
    preferredName: 'Sam',
    dateOfBirth: new Date('1991-08-08'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '919-38-5541',
    phonePrimary: '16155551801',
    email: 'samantha.lee@example.com',
    address: { line1: '600 Nicollet Mall', city: 'Minneapolis', state: 'MN', postalCode: '55402' },
    emergencyContact: { name: 'Peter Lee', relationship: 'Father', phone: '16155551802' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'Accountant',
    employer: 'Deloitte',
    patientProfileType: 'adult' as const,
    referralSource: 'Online Search',
  },
  {
    firstName: 'Kevin',
    lastName: 'Robinson',
    middleName: 'James',
    title: 'Mr.',
    dateOfBirth: new Date('1958-06-15'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '921-74-2289',
    phonePrimary: '18435551901',
    phoneSecondary: '18435551902',
    email: 'kevin.robinson@example.com',
    address: { line1: '115 Meeting St', city: 'Charleston', state: 'SC', postalCode: '29401' },
    emergencyContact: { name: 'Dorothy Robinson', relationship: 'Spouse', phone: '18435551903' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'portal' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Retired Police Officer',
    patientProfileType: 'adult' as const,
    referralSource: 'Family Referral',
    notes: 'Knee replacement surgery 2020. Annual x-rays required.',
  },
  {
    firstName: 'Lauren',
    lastName: 'Clark',
    dateOfBirth: new Date('2004-12-20'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '922-47-6613',
    phonePrimary: '16155552001',
    email: 'lauren.clark@example.com',
    address: { line1: '2401 Pennsylvania Ave NW', city: 'Washington', state: 'DC', postalCode: '20037' },
    emergencyContact: { name: 'Sandra Clark', relationship: 'Mother', phone: '16155552002' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'sms' as const,
    portalAccessEnabled: true,
    maritalStatus: 'single',
    occupation: 'College Student',
    employer: 'Georgetown University',
    patientProfileType: 'adult' as const,
    referralSource: 'Campus Health Referral',
  },
  {
    firstName: 'Tyler',
    lastName: 'Lewis',
    middleName: 'Grant',
    title: 'Mr.',
    dateOfBirth: new Date('1987-02-28'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '923-81-3354',
    phonePrimary: '13035552101',
    phoneSecondary: '13035552102',
    email: 'tyler.lewis@example.com',
    address: { line1: '1560 Blake St', line2: 'Unit 4', city: 'Denver', state: 'CO', postalCode: '80202' },
    emergencyContact: { name: 'Allison Lewis', relationship: 'Spouse', phone: '13035552103' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Data Scientist',
    employer: 'Palantir Technologies',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '1555 Blake St', city: 'Denver', state: 'CO', postalCode: '80202' },
    referralSource: 'Google Search',
  },
  {
    firstName: 'Natalie',
    lastName: 'Walker',
    middleName: 'Anne',
    preferredName: 'Nat',
    title: 'Ms.',
    dateOfBirth: new Date('1977-05-10'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '924-16-8877',
    phonePrimary: '16155552201',
    email: 'natalie.walker@example.com',
    address: { line1: '400 Church St', city: 'Nashville', state: 'TN', postalCode: '37219' },
    emergencyContact: { name: 'Greg Walker', relationship: 'Spouse', phone: '16155552202' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'married',
    occupation: 'Physical Therapist',
    employer: 'Vanderbilt University Medical Center',
    patientProfileType: 'adult' as const,
    referralSource: 'Insurance Directory',
  },
  {
    firstName: 'Brandon',
    lastName: 'Hall',
    dateOfBirth: new Date('2010-09-03'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '925-59-4421',
    phonePrimary: '12255552301',
    email: 'brandon.hall@example.com',
    address: { line1: '701 Poydras St', city: 'New Orleans', state: 'LA', postalCode: '70139' },
    emergencyContact: { name: 'Brenda Hall', relationship: 'Mother', phone: '12255552302' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'phone' as const,
    portalAccessEnabled: false,
    maritalStatus: 'single',
    patientProfileType: 'pediatric' as const,
    guardianEmployer: 'Tulane University',
    referralSource: 'Pediatrician Referral',
    notes: 'Minor - parent/guardian consent required for all procedures.',
  },
  {
    firstName: 'Rachel',
    lastName: 'Young',
    middleName: 'Marie',
    title: 'Dr.',
    dateOfBirth: new Date('1970-01-22'),
    gender: 'female' as const,
    sexAtBirth: 'female' as const,
    genderIdentity: 'female' as const,
    ssn: '926-92-6658',
    phonePrimary: '16085552401',
    phoneSecondary: '16085552402',
    email: 'rachel.young@example.com',
    address: { line1: '222 State St', city: 'Madison', state: 'WI', postalCode: '53703' },
    emergencyContact: { name: 'Mark Young', relationship: 'Spouse', phone: '16085552403' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'portal' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Physician',
    employer: 'UW Health',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '600 Highland Ave', city: 'Madison', state: 'WI', postalCode: '53792' },
    referralSource: 'Self Referral',
  },
  {
    firstName: 'Jason',
    lastName: 'Allen',
    middleName: 'Scott',
    title: 'Mr.',
    dateOfBirth: new Date('1982-12-11'),
    gender: 'male' as const,
    sexAtBirth: 'male' as const,
    genderIdentity: 'male' as const,
    ssn: '927-28-1193',
    phonePrimary: '19165552501',
    phoneSecondary: '19165552502',
    email: 'jason.allen@example.com',
    address: { line1: '1415 L Street', city: 'Sacramento', state: 'CA', postalCode: '95814' },
    emergencyContact: { name: 'Monica Allen', relationship: 'Spouse', phone: '19165552503' },
    preferredLanguage: 'en' as const,
    communicationPreference: 'email' as const,
    portalAccessEnabled: true,
    maritalStatus: 'married',
    occupation: 'Civil Engineer',
    employer: 'California Department of Transportation',
    patientProfileType: 'adult' as const,
    workAddress: { country: 'US', line1: '1120 N Street', city: 'Sacramento', state: 'CA', postalCode: '95814' },
    referralSource: 'Yelp Review',
    notes: 'Prefers fluoride-free treatments when possible.',
  },
];

const seedPatients = async () => {
  // Use a fixed seed user ID — falls back to first available user
  let seedUserId: string | undefined;

  try {
    const adminUser = await prisma.userod.findFirst({ orderBy: { UserNum: 'asc' } });
    if (adminUser) {
      seedUserId = adminUser.UserNum.toString();
    }
  } catch {
    // Proceed without a userId if lookup fails
  }

  let created = 0;
  let skipped = 0;

  for (const patientData of patients) {
    try {
      await patientService.createPatient(patientData, seedUserId);
      console.log(`  Created: ${patientData.firstName} ${patientData.lastName}`);
      created++;
    } catch (error: any) {
      if (error?.statusCode === 409 || error?.message?.includes('already exist')) {
        console.log(`  Skipped (duplicate): ${patientData.firstName} ${patientData.lastName}`);
        skipped++;
      } else {
        console.error(`  Failed: ${patientData.firstName} ${patientData.lastName} — ${error?.message}`);
      }
    }
  }

  console.log(`\nPatient seeding complete. Created: ${created}, Skipped: ${skipped}`);
};

seedPatients()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
