import dotenv from 'dotenv';
import connectDB, { prisma } from '../config/db';
import { getNextId } from '../utils/opendental-ids.util';

dotenv.config();

const medicationsList = [
  { name: 'Acetaminophen', rxCui: 161, notes: 'Analgesic and antipyretic' },
  { name: 'Ibuprofen', rxCui: 5640, notes: 'Nonsteroidal anti-inflammatory drug (NSAID)' },
  { name: 'Amoxicillin', rxCui: 723, notes: 'Beta-lactam antibiotic' },
  { name: 'Lisinopril', rxCui: 29046, notes: 'ACE inhibitor for hypertension' },
  { name: 'Atorvastatin', rxCui: 83367, notes: 'HMG-CoA reductase inhibitor (statin) for hypercholesterolemia' },
  { name: 'Metformin', rxCui: 6809, notes: 'Biguanide hypoglycemic agent for Type 2 diabetes' },
  { name: 'Albuterol', rxCui: 435, notes: 'Beta-2 adrenergic agonist bronchodilator' },
  { name: 'Levothyroxine', rxCui: 10582, notes: 'Synthetic thyroid hormone T4' },
  { name: 'Metoprolol', rxCui: 6918, notes: 'Beta-blocker for hypertension/angina' },
  { name: 'Amlodipine', rxCui: 17767, notes: 'Dihydropyridine calcium channel blocker' },
  { name: 'Omeprazole', rxCui: 7646, notes: 'Proton pump inhibitor (PPI) for GERD' },
  { name: 'Losartan', rxCui: 59744, notes: 'Angiotensin II receptor blocker (ARB)' },
  { name: 'Gabapentin', rxCui: 25480, notes: 'Anticonvulsant and neuropathic pain agent' },
  { name: 'Hydrochlorothiazide', rxCui: 5487, notes: 'Thiazide diuretic' },
  { name: 'Sertraline', rxCui: 36437, notes: 'Selective serotonin reuptake inhibitor (SSRI) antidepressant' },
  { name: 'Simvastatin', rxCui: 36567, notes: 'Statin for lipid management' },
  { name: 'Montelukast', rxCui: 154448, notes: 'Leukotriene receptor antagonist for asthma/allergies' },
  { name: 'Furosemide', rxCui: 4603, notes: 'Loop diuretic' },
  { name: 'Pantoprazole', rxCui: 4053, notes: 'Proton pump inhibitor (PPI)' },
  { name: 'Fluticasone', rxCui: 41126, notes: 'Corticosteroid anti-inflammatory' },
  { name: 'Escitalopram', rxCui: 321205, notes: 'SSRI antidepressant' },
  { name: 'Rosuvastatin', rxCui: 301542, notes: 'Statin for lipid management' },
  { name: 'Bupropion', rxCui: 42347, notes: 'Aminoketone antidepressant/smoking cessation aid' },
  { name: 'Amoxicillin/Clavulanate', rxCui: 17351, notes: 'Combination penicillin antibiotic' },
  { name: 'Prednisone', rxCui: 8640, notes: 'Glucocorticoid anti-inflammatory/immunosuppressant' },
  { name: 'Duloxetine', rxCui: 35467, notes: 'Serotonin-norepinephrine reuptake inhibitor (SNRI)' },
  { name: 'Trazodone', rxCui: 10737, notes: 'Serotonin antagonist and reuptake inhibitor (SARI)' },
  { name: 'Tamsulosin', rxCui: 153892, notes: 'Alpha-1 blocker for benign prostatic hyperplasia (BPH)' },
  { name: 'Carvedilol', rxCui: 20352, notes: 'Nonselective beta/alpha-1 blocker' },
  { name: 'Meloxicam', rxCui: 274783, notes: 'NSAID for arthritis' },
  { name: 'Potassium Chloride', rxCui: 8591, notes: 'Mineral electrolyte supplement' },
  { name: 'Clonazepam', rxCui: 2598, notes: 'Benzodiazepine anxiolytic/anticonvulsant' },
  { name: 'Clopidogrel', rxCui: 70589, notes: 'P2Y12 platelet inhibitor' },
  { name: 'Cyclobenzaprine', rxCui: 3002, notes: 'Skeletal muscle relaxant' },
  { name: 'Atenolol', rxCui: 1202, notes: 'Beta-blocker' },
  { name: 'Alprazolam', rxCui: 596, notes: 'Benzodiazepine anxiolytic' },
  { name: 'Dextroamphetamine/Amphetamine', rxCui: 227549, notes: 'Central nervous system stimulant for ADHD' },
  { name: 'Citalopram', rxCui: 2556, notes: 'SSRI antidepressant' },
  { name: 'Hydrocodone/Acetaminophen', rxCui: 214182, notes: 'Opioid combination analgesic' },
  { name: 'Oxycodone', rxCui: 7804, notes: 'Opioid analgesic' },
  { name: 'Pravastatin', rxCui: 36726, notes: 'Statin' },
  { name: 'Spironolactone', rxCui: 9997, notes: 'Aldosterone antagonist diuretic' },
  { name: 'Losartan/Hydrochlorothiazide', rxCui: 220977, notes: 'Combination antihypertensive' },
  { name: 'Zolpidem', rxCui: 60819, notes: 'Nonbenzodiazepine hypnotic' },
  { name: 'Apixaban', rxCui: 1364430, notes: 'Factor Xa inhibitor anticoagulant' },
  { name: 'Latanoprost', rxCui: 87586, notes: 'Prostaglandin analog for glaucoma' },
  { name: 'Ondansetron', rxCui: 7623, notes: '5-HT3 receptor antagonist antiemetic' },
  { name: 'Allopurinol', rxCui: 519, notes: 'Xanthine oxidase inhibitor for gout' },
  { name: 'Methylphenidate', rxCui: 6902, notes: 'CNS stimulant' },
  { name: 'Famotidine', rxCui: 4278, notes: 'H2 receptor antagonist' },
  { name: 'Lisinopril/Hydrochlorothiazide', rxCui: 220796, notes: 'Combination antihypertensive' },
  { name: 'Estradiol', rxCui: 4083, notes: 'Estrogen hormone' },
  { name: 'Budesonide/Formoterol', rxCui: 351297, notes: 'Combination corticosteroid/LABA inhaler' },
  { name: 'Glipizide', rxCui: 4832, notes: 'Sulfonylurea hypoglycemic' },
  { name: 'Cephalexin', rxCui: 2266, notes: 'First-generation cephalosporin antibiotic' },
  { name: 'Doxycycline', rxCui: 3640, notes: 'Tetracycline antibiotic' },
  { name: 'Lorazepam', rxCui: 6470, notes: 'Benzodiazepine' },
  { name: 'Fentanyl', rxCui: 4337, notes: 'Synthetic opioid analgesic' },
  { name: 'Warfarin', rxCui: 11289, notes: 'Vitamin K antagonist anticoagulant' },
  { name: 'Sitagliptin', rxCui: 593411, notes: 'DPP-4 inhibitor hypoglycemic' },
  { name: 'Sulfamethoxazole/Trimethoprim', rxCui: 10180, notes: 'Combination sulfonamide antibiotic' },
  { name: 'Clonidine', rxCui: 2599, notes: 'Alpha-2 adrenergic agonist' },
  { name: 'Buspirone', rxCui: 1820, notes: 'Anxiolytic' },
  { name: 'Finasteride', rxCui: 25025, notes: '5-alpha reductase inhibitor' },
  { name: 'Ranitidine', rxCui: 9143, notes: 'H2 antagonist' },
  { name: 'Naproxen', rxCui: 7243, notes: 'NSAID' },
  { name: 'Fluoxetine', rxCui: 4493, notes: 'SSRI' },
  { name: 'Diazepam', rxCui: 3322, notes: 'Benzodiazepine' },
  { name: 'Mupirocin', rxCui: 7212, notes: 'Topical antibiotic' },
  { name: 'Methocarbamol', rxCui: 6833, notes: 'Skeletal muscle relaxant' },
  { name: 'Liraglutide', rxCui: 897400, notes: 'GLP-1 receptor agonist' },
  { name: 'Semaglutide', rxCui: 1991302, notes: 'GLP-1 receptor agonist' },
  { name: 'Empagliflozin', rxCui: 1545653, notes: 'SGLT2 inhibitor hypoglycemic' },
  { name: 'Metronidazole', rxCui: 6922, notes: 'Nitroimidazole antibiotic/antiprotozoal' },
  { name: 'Baclofen', rxCui: 1304, notes: 'GABA-B agonist muscle relaxant' },
  { name: 'Amitriptyline', rxCui: 704, notes: 'Tricyclic antidepressant' },
  { name: 'Propranolol', rxCui: 8787, notes: 'Nonselective beta-blocker' },
  { name: 'Diclofenac', rxCui: 3355, notes: 'NSAID' },
  { name: 'Levetiracetam', rxCui: 25995, notes: 'Anticonvulsant' },
  { name: 'Hydroxyzine', rxCui: 5553, notes: 'Antihistamine/anxiolytic' },
  { name: 'Topiramate', rxCui: 38279, notes: 'Anticonvulsant' },
  { name: 'Aripiprazole', rxCui: 89013, notes: 'Atypical antipsychotic' },
  { name: 'Memantine', rxCui: 6718, notes: 'NMDA receptor antagonist for Alzheimer\'s' },
  { name: 'Sumatriptan', rxCui: 37305, notes: '5-HT1 receptor agonist triptan for migraine' },
  { name: 'Hydralazine', rxCui: 5456, notes: 'Direct vasodilator' },
  { name: 'Tizanidine', rxCui: 38210, notes: 'Alpha-2 agonist muscle relaxant' },
  { name: 'Ropinirole', rxCui: 79140, notes: 'Dopamine agonist' },
  { name: 'Benztropine', rxCui: 1419, notes: 'Anticholinergic' },
  { name: 'Risperidone', rxCui: 35636, notes: 'Atypical antipsychotic' },
  { name: 'Quetiapine', rxCui: 51272, notes: 'Atypical antipsychotic' },
  { name: 'Methotrexate', rxCui: 6851, notes: 'Antimetabolite immunosuppressant' },
  { name: 'Folic Acid', rxCui: 4481, notes: 'Vitamin supplement' },
  { name: 'Prednisolone', rxCui: 8638, notes: 'Corticosteroid' },
  { name: 'Hydrocortisone', rxCui: 5493, notes: 'Corticosteroid' },
  { name: 'Triamcinolone', rxCui: 10767, notes: 'Corticosteroid' },
  { name: 'Nystatin', rxCui: 7578, notes: 'Antifungal' },
  { name: 'Fluconazole', rxCui: 4452, notes: 'Triazole antifungal' },
  { name: 'Valacyclovir', rxCui: 74614, notes: 'Antiviral' },
  { name: 'Acyclovir', rxCui: 296, notes: 'Antiviral' },
  { name: 'Oseltamivir', rxCui: 231365, notes: 'Neuraminidase inhibitor antiviral' },
  { name: 'Divalproex', rxCui: 3568, notes: 'Anticonvulsant/mood stabilizer' },
  { name: 'Lamotrigine', rxCui: 28439, notes: 'Anticonvulsant/mood stabilizer' },
  { name: 'Lithium Carbonate', rxCui: 6442, notes: 'Mood stabilizer' },
  { name: 'Donepezil', rxCui: 135447, notes: 'Acetylcholinesterase inhibitor for Alzheimer\'s' },
  { name: 'Carbidopa/Levodopa', rxCui: 2011, notes: 'Antiparkinson agent' },
  { name: 'Hydrocodone', rxCui: 5489, notes: 'Opioid analgesic' },
  { name: 'Morphine', rxCui: 7052, notes: 'Opioid analgesic' },
  { name: 'Tramadol', rxCui: 10689, notes: 'Synthetic opioid analgesic' },
  { name: 'Pregabalin', rxCui: 187832, notes: 'Anticonvulsant/neuropathic pain' },
  { name: 'Buprenorphine', rxCui: 1819, notes: 'Partial opioid agonist' },
  { name: 'Methadone', rxCui: 6813, notes: 'Opioid agonist' },
  { name: 'Tadalafil', rxCui: 313155, notes: 'PDE5 inhibitor' },
  { name: 'Sildenafil', rxCui: 135688, notes: 'PDE5 inhibitor' },
  { name: 'Alendronate', rxCui: 64323, notes: 'Bisphosphonate' },
  { name: 'Calcifediol', rxCui: 203874, notes: 'Vitamin D analog' },
  { name: 'Ergocalciferol', rxCui: 4022, notes: 'Vitamin D2' },
  { name: 'Cyanocobalamin', rxCui: 3012, notes: 'Vitamin B12' },
  { name: 'Ferrous Sulfate', rxCui: 4350, notes: 'Iron supplement' },
  { name: 'Potassium Citrate', rxCui: 8596, notes: 'Urinary alkalinizer' },
  { name: 'Oxybutynin', rxCui: 7808, notes: 'Anticholinergic for overactive bladder' },
  { name: 'Solifenacin', rxCui: 476054, notes: 'Anticholinergic' },
  { name: 'Dutasteride', rxCui: 308056, notes: '5-alpha reductase inhibitor' },
  { name: 'Silodosin', rxCui: 853036, notes: 'Alpha-1 blocker' },
  { name: 'Mirabegron', rxCui: 1308331, notes: 'Beta-3 adrenergic agonist' },
  { name: 'Hydroxyzine Pamoate', rxCui: 5554, notes: 'Antihistamine' },
  { name: 'Promethazine', rxCui: 8820, notes: 'Antihistamine/antiemetic' },
  { name: 'Meclizine', rxCui: 6680, notes: 'Antihistamine for vertigo' },
  { name: 'Metoclopramide', rxCui: 6909, notes: 'Dopamine antagonist prokinetic' },
  { name: 'Dicyclomine', rxCui: 3418, notes: 'Antispasmodic' },
  { name: 'Mesalamine', rxCui: 6843, notes: 'Aminosalicylate anti-inflammatory' },
  { name: 'Sulfasalazine', rxCui: 10185, notes: 'DMARD' },
  { name: 'Azathioprine', rxCui: 1253, notes: 'Immunosuppressant' },
  { name: 'Cyclosporine', rxCui: 3008, notes: 'Immunosuppressant' },
  { name: 'Tacrolimus', rxCui: 42316, notes: 'Calcineurin inhibitor immunosuppressant' },
  { name: 'Mycophenolate Mofetil', rxCui: 74044, notes: 'Immunosuppressant' },
  { name: 'Hydroxychloroquine', rxCui: 5521, notes: 'Antimalarial/DMARD' },
  { name: 'Leflunomide', rxCui: 76895, notes: 'DMARD' },
  { name: 'Colchicine', rxCui: 2683, notes: 'Antigout agent' },
  { name: 'Febuxostat', rxCui: 846660, notes: 'Xanthine oxidase inhibitor' },
  { name: 'Terbinafine', rxCui: 37793, notes: 'Antifungal' },
  { name: 'Ketoconazole', rxCui: 6133, notes: 'Antifungal' },
  { name: 'Clotrimazole', rxCui: 2623, notes: 'Topical antifungal' },
  { name: 'Griseofulvin', rxCui: 4986, notes: 'Antifungal' },
  { name: 'Itraconazole', rxCui: 28031, notes: 'Antifungal' },
  { name: 'Permethrin', rxCui: 8092, notes: 'Topical scabicide' },
  { name: 'Ivermectin', rxCui: 6040, notes: 'Anthelmintic' },
  { name: 'Albendazole', rxCui: 400, notes: 'Anthelmintic' },
  { name: 'Mebendazole', rxCui: 6672, notes: 'Anthelmintic' },
  { name: 'Praziquantel', rxCui: 8588, notes: 'Anthelmintic' },
  { name: 'Chloroquine', rxCui: 2358, notes: 'Antimalarial' },
  { name: 'Atovaquone/Proguanil', rxCui: 221063, notes: 'Antimalarial' },
  { name: 'Artemether/Lumefantrine', rxCui: 856403, notes: 'Antimalarial' },
  { name: 'Levofloxacin', rxCui: 82122, notes: 'Fluoroquinolone antibiotic' },
  { name: 'Ciprofloxacin', rxCui: 2582, notes: 'Fluoroquinolone antibiotic' },
  { name: 'Moxifloxacin', rxCui: 137976, notes: 'Fluoroquinolone antibiotic' },
  { name: 'Azithromycin', rxCui: 18631, notes: 'Macrolide antibiotic' },
  { name: 'Clarithromycin', rxCui: 21199, notes: 'Macrolide antibiotic' },
  { name: 'Erythromycin', rxCui: 4053, notes: 'Macrolide antibiotic' },
  { name: 'Clindamycin', rxCui: 2581, notes: 'Lincosamide antibiotic' },
  { name: 'Linezolid', rxCui: 220194, notes: 'Oxazolidinone antibiotic' },
  { name: 'Vancomycin', rxCui: 11124, notes: 'Glycopeptide antibiotic' },
  { name: 'Rifaximin', rxCui: 186960, notes: 'Rifamycin antibiotic' },
  { name: 'Nitrofurantoin', rxCui: 7425, notes: 'Nitrofuran antibacterial' },
  { name: 'Fosfomycin', rxCui: 4579, notes: 'Phosphonic acid antibiotic' },
  { name: 'Trimethoprim', rxCui: 10825, notes: 'Folate antagonist antibacterial' },
  { name: 'Amikacin', rxCui: 642, notes: 'Aminoglycoside antibiotic' },
  { name: 'Gentamicin', rxCui: 4734, notes: 'Aminoglycoside antibiotic' },
  { name: 'Tobramycin', rxCui: 10609, notes: 'Aminoglycoside antibiotic' },
  { name: 'Neomycin', rxCui: 7306, notes: 'Aminoglycoside antibiotic' },
  { name: 'Polymyxin B', rxCui: 8536, notes: 'Polypeptide antibiotic' },
  { name: 'Bacitracin', rxCui: 1292, notes: 'Polypeptide antibiotic' },
  { name: 'Chlorhexidine', rxCui: 2354, notes: 'Antiseptic disinfectant' },
  { name: 'Lidocaine', rxCui: 6387, notes: 'Local anesthetic' },
  { name: 'Benzocaine', rxCui: 1405, notes: 'Local anesthetic' },
  { name: 'Prilocaine', rxCui: 8718, notes: 'Local anesthetic' },
  { name: 'Articaine', rxCui: 125433, notes: 'Local dental anesthetic' },
  { name: 'Bupivacaine', rxCui: 1814, notes: 'Local anesthetic' },
  { name: 'Mepivacaine', rxCui: 6750, notes: 'Local anesthetic' },
  { name: 'Ropivacaine', rxCui: 137359, notes: 'Local anesthetic' },
  { name: 'Propofol', rxCui: 8859, notes: 'General anesthetic/sedative' },
  { name: 'Ketamine', rxCui: 6130, notes: 'General anesthetic/dissociative' },
  { name: 'Midazolam', rxCui: 6960, notes: 'Benzodiazepine sedative' },
  { name: 'Dexmedetomidine', rxCui: 125696, notes: 'Alpha-2 agonist sedative' },
  { name: 'Etomidate', rxCui: 4165, notes: 'General anesthetic' },
  { name: 'Succinylcholine', rxCui: 10134, notes: 'Depolarizing neuromuscular blocker' },
  { name: 'Rocuronium', rxCui: 73003, notes: 'Nondepolarizing neuromuscular blocker' },
  { name: 'Vecuronium', rxCui: 11130, notes: 'Nondepolarizing neuromuscular blocker' },
  { name: 'Cisatracurium', rxCui: 187834, notes: 'Nondepolarizing neuromuscular blocker' },
  { name: 'Neostigmine', rxCui: 7315, notes: 'Cholinesterase inhibitor' },
  { name: 'Sugammadex', rxCui: 853039, notes: 'Selective relaxant binding agent' },
  { name: 'Flumazenil', rxCui: 4429, notes: 'Benzodiazepine antagonist' },
  { name: 'Naloxone', rxCui: 7242, notes: 'Opioid antagonist' },
  { name: 'Epinephrine', rxCui: 3992, notes: 'Sympathomimetic catecholamine' },
  { name: 'Norepinephrine', rxCui: 7512, notes: 'Catecholamine vasopressor' },
  { name: 'Phenylephrine', rxCui: 8163, notes: 'Alpha-1 adrenergic agonist decongestant' }
];

const seedMedications = async () => {
  try {
    await connectDB();

    for (const medData of medicationsList) {
      const existing = await prisma.medication.findFirst({
        where: { MedName: medData.name },
      });

      if (existing) {
        console.log(`Medication "${medData.name}" already exists, skipping...`);
        continue;
      }

      const nextId = await getNextId('medication', 'MedicationNum');
      await prisma.medication.create({
        data: {
          MedicationNum: nextId,
          MedName: medData.name,
          RxCui: BigInt(medData.rxCui),
          Notes: medData.notes,
          IsHidden: 0,
          DateTStamp: new Date(),
        },
      });
      console.log(`✓ Seeded medication: ${medData.name}`);
    }

    console.log('\n✅ 200 Medications seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding medications:', error);
    process.exit(1);
  }
};

seedMedications();