import { roleService } from '../services/role.service.js';

const rolesToSeed = [
  {
    name: 'Admin',
    description: 'System Administrator',
    isSystemRole: true,
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": true, "read": true, "update": true, "delete": true },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": true, "read": true, "update": true, "delete": true },
      "ConsentForm": { "create": true, "read": true, "update": true, "delete": true },
      "TwoFactorAuth": { "create": true, "read": true, "update": true, "delete": true },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": true, "read": true, "update": true, "delete": true },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": true, "read": true, "update": true, "delete": true },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": true },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": true, "read": true, "update": true, "delete": true },
      "DSOPatients": { "create": true, "read": true, "update": true, "delete": true },
      "DSOProcs": { "create": true, "read": true, "update": true, "delete": true },
      "DSOProduction": { "create": true, "read": true, "update": true, "delete": true },
      "DSOProvs": { "create": true, "read": true, "update": true, "delete": true },
      "DSOAging": { "create": true, "read": true, "update": true, "delete": true },
      "DSOAppointments": { "create": true, "read": true, "update": true, "delete": true },
      "IntegrationPerio": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Manager',
    description: 'Manager role based on UI reference',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Hygienist',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'BI',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Front',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Dentist',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Assistant',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'Owner',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
  {
    name: 'IntegrationRole',
    permissions: {
      "AccountCredit": { "create": true, "read": true, "update": true, "delete": true },
      "AccountCreditPortions": { "create": false, "read": false, "update": false, "delete": false },
      "EmailSettings": { "create": true, "read": true, "update": true, "delete": true },
      "KioskSetup": { "create": true, "read": true, "update": true, "delete": true },
      "OperatorySetup": { "create": true, "read": true, "update": true, "delete": true },
      "PracticeInfo": { "create": true, "read": true, "update": true, "delete": true },
      "ProviderSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RemindersSetup": { "create": true, "read": true, "update": true, "delete": true },
      "RoleSetup": { "create": true, "read": true, "update": true, "delete": true },
      "UserSetup": { "create": true, "read": true, "update": true, "delete": true },
      "AncillaryTests": { "create": true, "read": true, "update": true, "delete": true },
      "DICOM": { "create": true, "read": true, "update": true, "delete": true },
      "MDHistory": { "create": true, "read": true, "update": true, "delete": true },
      "Patient": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTerminals": { "create": true, "read": true, "update": true, "delete": true },
      "AdminResetPassword": { "create": true, "read": true, "update": true, "delete": true },
      "MergeData": { "create": false, "read": false, "update": false, "delete": false },
      "ConsentForm": { "create": false, "read": false, "update": false, "delete": false },
      "TwoFactorAuth": { "create": false, "read": false, "update": false, "delete": false },
      "SyncDataAcrossLocations": { "create": true, "read": true, "update": true, "delete": true },
      "CommunicationActivity": { "create": true, "read": true, "update": true, "delete": true },
      "OperatoryFilters": { "create": false, "read": true, "update": false, "delete": false },
      "PatientFlags": { "create": true, "read": true, "update": true, "delete": true },
      "ManageSignedDocuments": { "create": false, "read": false, "update": false, "delete": false },
      "AdjunctiveTherapy": { "create": true, "read": true, "update": true, "delete": true },
      "Checklists": { "create": true, "read": true, "update": true, "delete": true },
      "DiagnosticOpinion": { "create": true, "read": true, "update": true, "delete": true },
      "Exam": { "create": true, "read": true, "update": true, "delete": true },
      "ProcedureCodes": { "create": true, "read": true, "update": true, "delete": true },
      "Products": { "create": true, "read": true, "update": true, "delete": true },
      "ProgressNotes": { "create": true, "read": true, "update": true, "delete": true },
      "Referral": { "create": true, "read": true, "update": true, "delete": true },
      "RX": { "create": true, "read": true, "update": true, "delete": true },
      "RXTemplates": { "create": true, "read": true, "update": true, "delete": true },
      "TreatmentPlan": { "create": true, "read": true, "update": true, "delete": true },
      "TPPresentation": { "create": true, "read": true, "update": true, "delete": true },
      "ClinicalSettings": { "create": true, "read": true, "update": true, "delete": true },
      "RecareSettings": { "create": true, "read": true, "update": true, "delete": true },
      "AIConversations": { "create": true, "read": true, "update": true, "delete": true },
      "Claim": { "create": true, "read": true, "update": true, "delete": true },
      "ClaimManagement": { "create": true, "read": true, "update": true, "delete": true },
      "EClaimConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "InsuranceCarrier": { "create": true, "read": true, "update": true, "delete": true },
      "InsurancePlan": { "create": true, "read": true, "update": true, "delete": true },
      "PatientPolicy": { "create": true, "read": true, "update": true, "delete": true },
      "Adjustment": { "create": true, "read": true, "update": true, "delete": true },
      "AdjustmentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "BillingConfiguration": { "create": true, "read": true, "update": true, "delete": true },
      "Deposit": { "create": true, "read": true, "update": true, "delete": true },
      "FeeGuides": { "create": true, "read": true, "update": true, "delete": true },
      "FinanceManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Invoice": { "create": true, "read": true, "update": true, "delete": true },
      "Payment": { "create": true, "read": true, "update": true, "delete": true },
      "PaymentTypes": { "create": true, "read": true, "update": true, "delete": true },
      "Refund": { "create": true, "read": true, "update": true, "delete": true },
      "Transfer": { "create": true, "read": true, "update": true, "delete": true },
      "BillingBackDate": { "create": true, "read": true, "update": true, "delete": true },
      "EditProcedureFees": { "create": true, "read": true, "update": true, "delete": false },
      "PrintBillingTransactions": { "create": true, "read": true, "update": true, "delete": true },
      "AdvancedReports": { "create": true, "read": true, "update": true, "delete": true },
      "AgingReports": { "create": true, "read": true, "update": true, "delete": true },
      "Dashboard": { "create": true, "read": true, "update": true, "delete": true },
      "DashboardGoals": { "create": true, "read": true, "update": true, "delete": true },
      "DepositSlip": { "create": true, "read": true, "update": true, "delete": true },
      "ProductionReports": { "create": true, "read": true, "update": true, "delete": true },
      "RecareReports": { "create": true, "read": true, "update": true, "delete": true },
      "Schedule": { "create": true, "read": true, "update": true, "delete": true },
      "KPI": { "create": false, "read": false, "update": false, "delete": false },
      "PaymentPlan": { "create": false, "read": false, "update": false, "delete": false },
      "GenerateProductionReport": { "create": true, "read": true, "update": true, "delete": true },
      "TimeClockSetup": { "create": true, "read": true, "update": true, "delete": true },
      "TaskManagement": { "create": true, "read": true, "update": true, "delete": true },
      "Automations": { "create": false, "read": false, "update": false, "delete": false },
      "DSOPatients": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProcs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProduction": { "create": false, "read": false, "update": false, "delete": false },
      "DSOProvs": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAging": { "create": false, "read": false, "update": false, "delete": false },
      "DSOAppointments": { "create": false, "read": false, "update": false, "delete": false },
      "IntegrationPerio": { "create": false, "read": false, "update": false, "delete": false },
      "ImagingAdvancedSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingTemplatesSettings": { "create": true, "read": true, "update": true, "delete": true },
      "ImagingDeviceSettings": { "create": true, "read": true, "update": true, "delete": true }
    }
  },
];

async function seedData() {
  console.log('Starting seed process...');
  for (const role of rolesToSeed) {
    try {
      console.log(`Checking if role '${role.name}' exists...`);
      const existing = await roleService.getRoleByName(role.name);

      if (existing) {
        console.log(`Updating existing role '${role.name}'...`);
        await roleService.updateRole(existing._id, {
          permissions: role.permissions as any
        });
      } else {
        console.log(`Creating new role '${role.name}'...`);
        await roleService.createRole({
          name: role.name,
          description: role.description || '',
          permissions: role.permissions as any,
          isSystemRole: false
        });
      }
      console.log(`Successfully processed role: ${role.name}`);
    } catch (error) {
      console.error(`Error processing role ${role.name}:`, error);
    }
  }
  console.log('Seed process completed successfully!');
  process.exit(0);
}

seedData().catch(err => {
  console.error('Fatal error during seed:', err);
  process.exit(1);
});
